/**
 * generated by Xtext 2.12.0
 */
package com.coffee.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * Class to test the correct parsing of HLVL
 * @author Angela Villota
 * @version HLVL V4
 * November 2018
 */
@RunWith(XtextRunner.class)/* 
@InjectWith(/* name is null */) */
@SuppressWarnings("all")
public class HlvlParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Inject
  @Extension
  private ParseHelper _parseHelper;
  
  /**
   * Method to test the interpretation of an empty program
   */
  @Test
  public void emptyModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field HlvlParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
