/**
 * generated by Xtext 2.12.0
 */
package com.coffee.ide;

import com.coffee.HlvlStandaloneSetup;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HlvlIdeSetup extends HlvlStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from HlvlRuntimeModule to Module"
      + "\nType mismatch: cannot convert from HlvlIdeModule to Module");
  }
}
