/*
 * generated by Xtext 2.17.1
 */
package com.coffee.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHlvlScopeProvider extends DelegatingScopeProvider {
}
