/**
 * generated by Xtext 2.12.0
 */
package com.coffee;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HlvlStandaloneSetup /* implements HlvlStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type HlvlStandaloneSetup");
  }
}
